Add support for reading packets from saved pcap file
sensorfu/luomu-libpcap pull request #40
Opened 2021-12-19 14:20 UTC by jtt

Adds `Pcap::offline()` method to start reading packets from file instead of reading live traffic from interface.

2021-12-19 20:04 UTC, oherrala requested changes

2021-12-20 07:08 UTC, jtt commented on luomu-libpcap/src/functions.rs
> +/// `pcap_open_offline()` is used to open given savwfile for reading.
Fixed.

2021-12-20 07:09 UTC, jtt commented on luomu-libpcap/src/functions.rs
> +pub fn pcap_open_offline(savefile: &str) -> Result<PcapT> {
Fixed.

2021-12-20 07:09 UTC, jtt commented on luomu-libpcap/examples/offline.rs
> +        count += 1;
Fixed

2021-12-20 07:51 UTC, oherrala approved these changes

2021-12-20 08:19 UTC, merged